variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "region" {}
variable "compartment_id" {}
variable "subnet_id" {}
variable "source_id" {}
variable "shape" {}
variable "display_name" {}
variable "ssh_pub_key_path" {}
