variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "region" {}
variable "compartment_id" {}
variable "vcn_display_name" {}
variable "vcn_cidr" {}
variable "vcn_dns_label" {}
variable "security_list_private_subnet_name" {}
variable "security_list_public_subnet_name" {}
variable "private_subnet_cidr_block" {}
